-- MySQL Script generated by MySQL Workbench
-- Wed Feb 18 13:34:32 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reservation_salles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reservation_salles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reservation_salles` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `reservation_salles` ;

-- -----------------------------------------------------
-- Table `reservation_salles`.`salles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_salles`.`salles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `capacite` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reservation_salles`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_salles`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `role` VARCHAR(20) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reservation_salles`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservation_salles`.`reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `debut` DATETIME NOT NULL,
  `fin` DATETIME NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  `salle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservations_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_reservation_salle` (`salle_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_salle`
    FOREIGN KEY (`salle_id`)
    REFERENCES `reservation_salles`.`salles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_reservations_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `reservation_salles`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
